blacklist = [
  'Canada', 'Chile', 'Argentina', 'Venezuela', 'UK', 'Spain', 'Philippines', 
  'Michigan', 'Maryland', 'New York', 'Washington', 'Colorado', 
  'Ontario', 'ontario', 'New Westminster', # Important
  'MN', 'NJ', 'FL', 'MI', 'IL', 'TX', 'MD', 'PA', 'CO', 'CT', 'BC'
]
state = 'CA'
counties = {
  'Los Angeles': [
    'Agoura Hills',
    'Alhambra',
    'Arcadia',
    'Artesia',
    'Azusa',
    'Baldwin Park',
    'Bell',
    'Bell Gardens',
    'Bellflower',
    'Beverly Hills',
    'Bradbury',
    'Burbank',
    'CalabasCarson',
    'Cerritos',
    'Claremont',
    'Commerce',
    'Compton',
    'Covina',
    'Cudahy',
    'Culver City',
    'Diamond Bar',
    'Downey',
    'Duarte',
    'El Monte',
    'El Segundo',
    'Gardena',
    'Glendale',
    'Glendora',
    'Hawaiian Gardens',
    'Hawthorne',
    'Hermosa Beach',
    'Hidden Hills',
    'Huntington Park',
    'Industry',
    'Inglewood',
    'Irwindale',
    'La Canada-Flintridge',
    'La Habra Heights',
    'La Mirada',
    'La Puente',
    'La Verne',
    'Lakewood',
    'Lancaster',
    'Lawndale',
    'Lomita',
    'Long Beach',
    'Los Angeles',
    'Lynwood',
    'Malibu',
    'Manhattan Beach',
    'Maywood',
    'Monrovia',
    'Montebello',
    'Monterey Park',
    'Norwalk',
    'Palmdale',
    'Palos Verdes Estates',
    'Paramount',
    'Pasadena',
    'Pico Rivera',
    'Pomona',
    'Rancho Palos Verdes',
    'Redondo Beach',
    'Rolling Hills',
    'Rolling Hills Estates',
    'Rosemead',
    'San Dimas',
    'San Fernando',
    'San Gabriel',
    'San Marino',
    'Santa Clarita',
    'Santa Fe Springs',
    'Santa Monica',
    'Sierra Madre',
    'Signal Hill',
    'South El Monte',
    'South Gate',
    'South Pasadena',
    'Temple City',
    'Torrance',
    'Vernon',
    'Walnut',
    'West Covina',
    'West Hollywood',
    'Westlake Village',
    'Whittier'
  ],
  'Orange': [
    'Anaheim',
    'Brea',
    'Buena Park',
    'Costa Mesa',
    'Cypress',
    'Dana Point',
    'Fountain Valley',
    'Fullerton',
    'Garden Grove',
    'Huntington Beach',
    'Irvine',
    'La Habra',
    'La Palma',
    'Laguna Beach',
    'Laguna Hills',
    'Laguna Niguel',
    'Lake Forest',
    'Los Alamitos',
    'Mission Viejo',
    'Newport Beach',
    'Orange',
    'Placentia',
    'San Clemente',
    'San Juan Capistrano',
    'Santa Ana',
    'Seal Beach',
    'Stanton',
    'Tustin',
    'Villa Park',
    'Westminster',
    'Yorba Linda'
  ],
  'Riverside': [
    'Banning',
    'Beaumont',
    'Blythe',
    'Calimesa',
    'Canyon Lake',
    'Cathedral City',
    'Coachella',
    'Corona',
    'Desert Hot Springs',
    'Hemet',
    'Indian Wells',
    'Indio',
    'La Quinta',
    'Lake Elsinore',
    'Moreno Valley',
    'Murrieta',
    'Norco',
    'Palm Desert',
    'Palm Springs',
    'Perris',
    'Rancho Mirage',
    'Riversi',
    'San Jacinto',
    'Temecula'
  ],
  'San Bernardino': [
    'Adelanto',
    'Apple Valley',
    'Barstow',
    'Big Bear Lake',
    'Chino',
    'Chino Hills',
    'Colton',
    'Fontana',
    'Grand Terrace',
    'Hesperia',
    'Highland',
    'Loma Linda',
    'Montclair',
    'Needles',
    'Ontario',
    'Rancho Cucamonga',
    'Redlands',
    'Rialto',
    'San Bernardino',
    'Twentynine Palms',
    'Upland',
    'Victorville',
    'Yucaipa',
    'Yucca Valley'
  ],
  'San Diego': [
    'Carlsbad',
    'Chula Vista',
    'Coronado',
    'Del Mar',
    'El Cajon',
    'Encinitas',
    'Escondido',
    'Imperial Beach',
    'La Mesa',
    'Lemon Grove',
    'National City',
    'Oceanside',
    'Poway',
    'San Diego',
    'San Marcos',
    'Santee',
    'Solana Beach',
    'Vista'
  ]
}